services:
  siem:
    build:
      context: .
      dockerfile: Dockerfile.siem
    ports:
      - "9000:9000"
    volumes:
      - ./data:/app/data
    environment:
      - DB_PATH=/app/data/audit_siem.db
      - PYTHONUNBUFFERED=1  # <--- КРИТИЧНО: отключает задержку логов
    restart: always

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "8000:8000"
    depends_on:
      - siem
    environment:
      - SIEM_URL=http://siem:9000
      - PYTHONUNBUFFERED=1  # <--- КРИТИЧНО: логи шлюза полетят сразу
    restart: always
